module Games
  module Simulations
    module CardsGame
      class Game
        @card_count: Integer

        @players: Array[Player]

        @strategy: Strategy::_Distributable

        attr_reader rounds: Integer

        attr_accessor players: Array[Player]

        MIN_CARDS: Integer
        MAX_CARDS: Integer
        MIN_PLAYERS: Integer
        MAX_PLAYERS: Integer

        type game_config = {?player_count: ::Integer, ?card_count: ::Integer, ?mode: Symbol } | ActionController::Parameters
        def self.from: (game_config config) -> Game

        def play: () -> GameResult

        def reset: () -> void

        private

        def initialize: (?player_count: ::Integer, ?card_count: ::Integer, ?mode: ::Symbol) -> void

        def do_play: () -> GameResult

        def players_by_rank: () -> Array[PlayerResult]

        def distribute_cards: () -> void
      end
    end
  end
end
