module Games
  class CardsController < ApplicationController
    @game_result: Cards::GameResult

    def create: () -> untyped

    private

    def card_game_items: () -> ActionController::Parameters
  end
end
