<% quotes_env = -> (key, fallback) { ENV.fetch("QUOTES_BROADCAST_#{key.upcase}", fallback).to_i  == 1 } %>

production:
  broadcast:
    enabled: <%= quotes_env.("enabled", 0) %>
    global: <%= quotes_env.("global", 1) %>
development:
  broadcast:
    enabled: <%= quotes_env.("enabled", 1) %>
    global: <%= quotes_env.("global", 1) %>
test:
  broadcast:
    enabled: false
    global: false