module Games
  class CardsController < ApplicationController
    @game_result: Cards::GameResult

    def simulate: () -> void

    private

    def card_game_items: () -> { card_count: Integer, player_count: Integer }
  end
end
