module Quotes
  class YodaChannel < ApplicationCable::Channel

    def subscribed: () -> untyped

    def unsubscribed: -> untyped

    def update_interval: (Hash[untyped, untyped] data) -> untyped

    private

    def broadcast?: -> bool

    def broadcast_key: -> ::String

    def global_interval: (?interval: Integer | nil) -> Integer

    def global_broadcast?: -> bool

    type quote_message_type = {action: ::String, body: { id: Integer, quote: ::String}}
    def quote_message: -> quote_message_type

    type interval_message_type = {action: ::String, body: { interval: Integer}}
    def interval_message: (Integer interval) -> interval_message_type

    def interval_valid?: (Integer | nil interval) -> bool

    def send_message: -> Proc

    def start_broadcast: (?key: ::String, ?interval: ::Integer) -> untyped

    def stop_broadcast: (?force: bool) -> untyped
  end
end