class Games::GamesController < ApplicationController
  @games_games: untyped

  @games_game: untyped

  # GET /games/games or /games/games.json
  def index: () -> untyped

  # GET /games/games/1 or /games/games/1.json
  def show: () -> nil

  # GET /games/games/new
  def new: () -> untyped

  # GET /games/games/1/edit
  def edit: () -> nil

  # POST /games/games or /games/games.json
  def create: () -> untyped

  # PATCH/PUT /games/games/1 or /games/games/1.json
  def update: () -> untyped

  # DELETE /games/games/1 or /games/games/1.json
  def destroy: () -> untyped

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_games_game: () -> untyped

  # Only allow a list of trusted parameters through.
  def games_game_params: () -> untyped
end
